{
 "title": "Estadisticas Capacidad",
 "description": "Estadisticas Capacidad",
 "tags": [ "cpai" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "aplicacion", "query": "label_values(label_cliente)" }
  ]
 },
 "panels": [
  {
   "title": "% Uso memoria RAM",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{container_name!=\"POD\", container_name!=\"\"} * on(namespace) group_left(label_name) kube_namespace_labels{label_cliente=~\"$aplicacion*\"}) / sum(kube_resourcequota{resource=\"limits.memory\",type=\"used\"} * on(namespace) group_left(label_name) kube_namespace_labels{label_cliente=~\"$aplicacion*\"}) *100"
    }
   ]
  },
  {
   "title": "% Uso CPU",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{namespace=~\".*\"} * on(namespace) group_left(label_name) kube_namespace_labels{label_cliente=~\"$aplicacion*\"}) / sum(kube_resourcequota{resource=\"limits.cpu\",type=\"used\"} * on(namespace) group_left(label_name) kube_namespace_labels{label_cliente=~\"$aplicacion*\"})* 100"
    }
   ]
  },
  {
   "title": "% Uso Disco",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes) * on(namespace) group_left(label_name) kube_namespace_labels{label_cliente=~\"$aplicacion*\"}) / sum(max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_capacity_bytes) * on(namespace) group_left(label_name) kube_namespace_labels{label_cliente=~\"$aplicacion*\"})* 100"
    }
   ]
  },
  {
   "title": "Resumen",
   "type": "table-old",
   "gridPos": { "h": 5, "w": 23, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "max by (kube_namespace_labels,label_cliente) (kube_namespace_labels{label_cliente=~\"$aplicacion*\"} * on(namespace) group_left(label_name) kube_namespace_labels{label_cliente=~\"$aplicacion*\"})"
    },
    {
     "expr": "count(kube_namespace_created * on(namespace) group_left(label_name) kube_namespace_labels{label_cliente=~\"$aplicacion*\"})"
    },
    {
     "expr": "count(kube_pod_status_phase{phase=\"Running\"} * on(namespace) group_left(label_name) kube_namespace_labels{label_cliente=~\"$aplicacion*\"} > 0)"
    },
    {
     "expr": "sum((kube_persistentvolumeclaim_info) * on(namespace) group_left(label_name) kube_namespace_labels{label_cliente=~\"$aplicacion*\"})"
    },
    {
     "expr": "sum(max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_capacity_bytes) * on(namespace) group_left(label_name) kube_namespace_labels{label_cliente=~\"$aplicacion*\"})"
    },
    {
     "expr": "sum(max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes) * on(namespace) group_left(label_name) kube_namespace_labels{label_cliente=~\"$aplicacion*\"})"
    },
    {
     "expr": "sum(max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_available_bytes) * on(namespace) group_left(label_name) kube_namespace_labels{label_cliente=~\"$aplicacion*\"})"
    },
    {
     "expr": "sum(kube_resourcequota{resource=\"limits.cpu\",type=\"hard\"} * on(namespace) group_left(label_name) kube_namespace_labels{label_cliente=~\"$aplicacion*\"})"
    },
    {
     "expr": "sum(kube_resourcequota{resource=\"limits.cpu\",type=\"used\"} * on(namespace) group_left(label_name) kube_namespace_labels{label_cliente=~\"$aplicacion*\"})"
    },
    {
     "expr": "sum(kube_resourcequota{resource=\"limits.memory\",type=\"hard\"} * on(namespace) group_left(label_name) kube_namespace_labels{label_cliente=~\"$aplicacion*\"})"
    },
    {
     "expr": "sum(kube_resourcequota{resource=\"limits.memory\",type=\"used\"} * on(namespace) group_left(label_name) kube_namespace_labels{label_cliente=~\"$aplicacion*\"})"
    }
   ]
  },
  {
   "title": "Número de Namespaces",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 11 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(kube_namespace_created * on(namespace) group_left(label_name) kube_namespace_labels{label_cliente=~\"$aplicacion*\"})",
     "legendFormat": "{$entorno}{$aplicacion} ({{pod}})"
    }
   ]
  },
  {
   "title": "Namespaces",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 19, "x": 4, "y": 11 },
   "targets": [
    {
     "expr": "kube_namespace_created * on(namespace) group_left(label_name) kube_namespace_labels{label_cliente=~\"$aplicacion*\"}",
     "legendFormat": "{$entorno}{$aplicacion} ({{namespace}})"
    }
   ]
  },
  {
   "title": "Número de Pods",
   "type": "singlestat",
   "gridPos": { "h": 11, "w": 4, "x": 0, "y": 17 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Running\"} * on(namespace) group_left(label_name) kube_namespace_labels{label_cliente=~\"$aplicacion*\"} > 0)",
     "legendFormat": "{$entorno}{$aplicacion} ({{pod}})"
    }
   ]
  },
  {
   "title": "Pods",
   "type": "table-old",
   "gridPos": { "h": 11, "w": 19, "x": 4, "y": 17 },
   "targets": [
    {
     "expr": "kube_pod_status_phase{phase=\"Running\"} * on(namespace) group_left(label_name) kube_namespace_labels{label_cliente=~\"$aplicacion*\"} > 0"
    }
   ]
  },
  {
   "title": "Nº PVCs",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 28 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(kube_persistentvolumeclaim_info * on(namespace) group_left(label_name) kube_namespace_labels{label_cliente=~\"$aplicacion*\"})",
     "legendFormat": "{$entorno}{$aplicacion} ({{pod}})"
    }
   ]
  },
  {
   "title": "PVCs",
   "type": "table-old",
   "gridPos": { "h": 18, "w": 19, "x": 4, "y": 28 },
   "targets": [
    {
     "expr": "(kube_persistentvolumeclaim_info) * on(namespace) group_left(label_name) kube_namespace_labels{label_cliente=~\"$aplicacion*\"}"
    },
    {
     "expr": "max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_capacity_bytes)  * on(namespace) group_left(label_name) kube_namespace_labels{label_cliente=~\"$aplicacion*\"} "
    },
    {
     "expr": "max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes) * on(namespace) group_left(label_name) kube_namespace_labels{label_cliente=~\"$aplicacion*\"} "
    },
    {
     "expr": "max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_available_bytes) * on(namespace) group_left(label_name) kube_namespace_labels{label_cliente=~\"$aplicacion*\"} "
    }
   ]
  },
  {
   "title": "Espacio asignado",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 34 },
   "format": "bytes",
   "valueName": "first",
   "targets": [
    {
     "expr": "sum(max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_capacity_bytes) * on(namespace) group_left(label_name) kube_namespace_labels{label_cliente=~\"$aplicacion*\"})\n"
    }
   ]
  },
  {
   "title": "Memoria asignada",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 40 },
   "format": "bytes",
   "valueName": "first",
   "targets": [
    {
     "expr": "sum(kube_resourcequota{resource=\"limits.memory\",type=\"hard\"} * on(namespace) group_left(label_name) kube_namespace_labels{label_cliente=~\"$aplicacion*\"})\n"
    }
   ]
  }
 ]
}